services:
  conduit:
    image: matrixconduit/matrix-conduit:latest-commit-0c2cfda3
    volumes:
      - conduit-data:/var/lib/matrix-conduit/
    environment:
      CONDUIT_SERVER_NAME: conduit # EDIT THIS
      CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
      CONDUIT_DATABASE_BACKEND: rocksdb
      CONDUIT_PORT: 6167
      CONDUIT_MAX_REQUEST_SIZE: 20000000 # in bytes, ~20 MB
      CONDUIT_ALLOW_REGISTRATION: 'true'
      CONDUIT_ALLOW_FEDERATION: 'true'
      CONDUIT_ALLOW_CHECK_FOR_UPDATES: 'false'
      CONDUIT_TRUSTED_SERVERS: '[]'
      #CONDUIT_MAX_CONCURRENT_REQUESTS: 100
      #CONDUIT_LOG: warn,rocket=off,_=off,sled=off
      CONDUIT_ADDRESS: 0.0.0.0
      CONDUIT_CONFIG: '' # Ignore this
    ports:
      - 6167:6167

  ooye:
    depends_on:
      - conduit
    image: ooye
    build: .
    environment:
      SERVER_NAME: localhost
      SERVER_ORIGIN: http://conduit:6167
      ADMIN_INVITE: zicklag@localhost
      URL: http://ooye:6693
      HS_TOKEN: 8aa66039222ca2729421e4d600906cb17d39bf2e30048b3e24d1d7979704f229
      AS_TOKEN: ff42641357750bc24ff860551da787f31f6acb750202922e8d87b5dfd08e8940
    ports:
      - 6693:6693
    volumes:
      - ooye-data:/app/db

volumes:
  conduit-data:
  ooye-data:
